### ISSUE TITLE
error with mac compile

### ISSUE THREAD

**Issue by bumbacoin** [CooleRRSA/crave#1]
attempting an OSX qt build with boost 1.57 i get this error.

In file included from ../src/net.cpp:5:
In file included from ../src/db.h:9:
In file included from ../src/serialize.h:22:
In file included from ../src/allocators.h:10:
In file included from /opt/local/include/boost/thread/once.hpp:20:
In file included from /opt/local/include/boost/thread/pthread/once_atomic.hpp:19:
In file included from /opt/local/include/boost/bind.hpp:22:
/opt/local/include/boost/bind/bind.hpp:253:36: error: cannot initialize a parameter of type 'void *' with an lvalue of type 'long'
        unwrapper<F>::unwrap(f, 0)(a[base_type::a1_]);
                                   ^~~~~~~~~~~~~~~~~
/opt/local/include/boost/bind/bind_template.hpp:20:27: note: in instantiation of function template specialization 'boost::_bi::list1<boost::_bi::value<long> >::operator()<void (*)(void *), boost::_bi::list0>' requested here
        BOOST_BIND_RETURN l_(type<result_type>(), f_, a, 0);
                          ^
/opt/local/include/boost/thread/detail/thread.hpp:116:17: note: in instantiation of member function 'boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > >::operator()' requested here
                f();
                ^
/opt/local/include/boost/thread/pthread/thread_heap_alloc.hpp:47:24: note: in instantiation of member function 'boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > >::run' requested here
            return new T(a1);
                       ^
/opt/local/include/boost/thread/pthread/thread_heap_alloc.hpp:73:20: note: in instantiation of function template specialization 'boost::detail::heap_new_impl<boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > >, boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > &>' requested here
            return heap_new_impl<T,A1&>(a1);
                   ^
/opt/local/include/boost/thread/detail/thread.hpp:230:52: note: in instantiation of function template specialization 'boost::detail::heap_new<boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > >, boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > >' requested here
            return detail::thread_data_ptr(detail::heap_new<detail::thread_data<F> >(f));
                                                   ^
/opt/local/include/boost/thread/detail/thread.hpp:390:25: note: in instantiation of function template specialization 'boost::thread::make_thread_info<boost::_bi::bind_t<void, void (*)(void *), boost::_bi::list1<boost::_bi::value<long> > > >' requested here
            thread_info(make_thread_info(boost::bind(boost::type<void>(),f,a1)))
                        ^
../src/net.cpp:1840:5: note: in instantiation of function template specialization 'boost::thread::thread<void (*)(void *), long>' requested here
    boost::thread(&ThreadIRCSeed, NULL);
    ^
1 warning and 1 error generated.
make: *** [build/net.o] Error 1

**Comment by CooleRRSA** [comment]
Some troubles with IRC integrations.
You need disable ../src/net.cpp:1840 line.
Wallet will connected to network through DNS Seeding.

**Comment by CooleRRSA** [comment]
Fixed by https://github.com/CooleRRSA/crave/commit/a28b5d86df0c4a7f607ab9d91f64fe88d84e15a3
